urls.py
from django.conf.urls.defaults import *

from pyurl.settings import MIN_HASH_LEN, MAX_HASH_LEN, VALID_HASH_CHARS
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^willowvillagesquare/', include('willowvillagesquare.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^(XML)?RPC2\/?$', 'pyurl.rpc4django.views.serve_rpc_request'),
    url(r'^googlehostedservice.html$', 'pyurl.views.goog', name='googlehostedservice'),
    url(r'^RPC2$', 'pyurl.rpc4django.views.serve_rpc_request', name='rpc'),
    url(r'^(index\/?)?$', 'pyurl.views.index', name='site-homepage'),
    url(r'^create\/?$', 'pyurl.views.create', name='create'),
    url(r'^preview\/([%s]{%s,%s})\/?$' % (VALID_HASH_CHARS, MIN_HASH_LEN,
        MAX_HASH_LEN), 'pyurl.views.preview', name='preview'),
    (r'^admin\/', include(admin.site.urls)),
    url(r'^([%s]{%s,%s})$' % (VALID_HASH_CHARS, MIN_HASH_LEN, MAX_HASH_LEN),
        'pyurl.views.forward', name='forward'),
    #(r'^admin/', include(admin.site.urls)),
    #(r'^media/(.*)$', 'django.views.main.serve', {'document_root': './admin_media'}),
#    (r'^site_media/(.*)$', 'django.views.static.serve', {'document_root': '/path/to/folder/media'}),
)

models.py
from datetime import datetime

from django.db import models
from django.core.exceptions import ObjectDoesNotExist

from pyurl.helpers.static_callable import Callable
from pyurl.settings import (MAX_PATH_LEN, MIN_HASH_LEN, MAX_HASH_LEN,
                            MAX_HASH_COLLISIONS_ALLOWED)
from pyurl import settings


#MAX_PATH_LEN = 2068

#MIN_HASH_LEN = 2
#MAX_HASH_LEN = 8

#MAX_HASH_COLLISIONS_ALLOWED = 10





PROTOCOLS = (
    (1, 'http'),
    (2, 'https'),
    (3, 'ftp'),
    (4, 'irc'),
    (5, 'aim'),
)

#class Protocol(models.Model):
#    name = models.CharField(max_length=5, choices=PROTOCOLS)
#
#    def __unicode__(self):
#        return self.name


class Url(models.Model):
    #protocol = models.ForeignKey(Protocol)
    path = models.CharField(max_length=MAX_PATH_LEN)
    hash = models.CharField(max_length=MAX_HASH_LEN)
    # DateTime of creation.
    #stamp_created = models.fields.DateTimeField(default=datetime.today)
    stamp_created = models.fields.DateTimeField(auto_now=True,
        auto_now_add=True)

    #def __init__(self, *args, **kw):

    def __unicode__(self):
        return self.path

    def __get_base_url(self):
        return '%s' % getattr(settings, 'SITE_BASE_URL')

    base_url = property(__get_base_url)

    def __get_short_url(self):
        return '%s/%s' % (getattr(settings, 'SITE_BASE_URL'), self.hash)

    short_url = property(__get_short_url)

    def __get_target_url(self):
        return '%s' % (self.path)

#    def __set_target_url(self, s):
        #from pyurl.helpers.tools import parse_url, unique_hash
        #prot, path = parse_url(url)
        #try:
            # Check to see if the url already exists.
            #u = Url.objects.get(protocol=Protocol.objects.get(name=prot), path=path)
        #except ObjectDoesNotExist:
            #hash = unique_hash(url)
            #u = Url(protocol=Protocol.objects.get(name=prot), path=path, hash=hash)

    target_url = property(__get_target_url)#, __set_target_url)

    def __get_short_url_len(self):
        return len(self.__get_short_url())

    short_url_len = property(__get_short_url_len)

    def __get_target_url_len(self):
        return len(self.__get_target_url())

    target_url_len = property(__get_target_url_len)
#    def factory(url):
        #from pyurl.helpers.tools import parse_url, unique_hash
        #prot, path = parse_url(url)
        #try:
            # Check to see if the url already exists.
            #u = Url.objects.get(protocol=Protocol.objects.get(name=prot), path=path)
        #except ObjectDoesNotExist:
            #hash = unique_hash(url)
            #u = Url(protocol=Protocol.objects.get(name=prot), path=path, hash=hash)
        #return u
#            # Make sure the exception is not on the hash column.
#            if (str(e).find('columns protocol_id, path are not unique') != -1 or
#                str(e).find('conflicts with persistent instance') != -1):
#            #if str(e).find('column hash is not unique') == -1
#                session.rollback()
#                return Url.query.filter_by(protocol=Protocol.get(prot),
#                    path=path).one()
#            raise e

#    factory = Callable(factory)

templates/base.html
<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head>
<link rel="icon" href="favicon.ico" type="image/x-icon" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="robots.txt" />
<meta name="keywords" content="" />
    <title>{% block title %}Default Title{% endblock %} | MySite</title>
    <link rel="stylesheet" type="text/css" href="styles/site.css" />
  </head>
  <body>
    <div class="nav">
      <a href="/">home</a>
    </div>
{% block content %}{% endblock %}

  </body>
</html>

templates/create.html
{% extends "base.html" %}

{% block title %}Shorten a URL{% endblock %}

{% block content %}
{% if url %}
<h2>Shortened URL successfully created!</h2>
The following URL:
<p class="indent_link">
	<a href="{{ url.target_url }}">{{ url.target_url }}</a>
</p>
consists of {{ url.target_url_len }} characters, and resulted in a URL which is {{ url.short_url_len }} characters long:
<p class="indent_link">
	<a href="{{ url.short_url }}">{{ url.short_url }}</a>
</p>
<p class="indent_link">
	<a href="{{ url.base_url }}/preview/{{ url.hash }}">{{ url.base_url }}/preview/{{ url.hash }}</a>
</p>

<h1>Create another short URL</h1>
{% else %}
<h1>Shorten a URL</h1>
{% endif %}
{% include "url_form.html" %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Main Page{% endblock %}

{% block content %}
Welcome.
<br />
<br />
{% include "url_form.html" %}
{% endblock %}

templates/preview.html
{% extends "base.html" %}

{% block title %}URL Preview{% endblock %}

{% block content %}
The following URL:
<p class="indent_link">
	<a href="{{ url.target_url }}">{{ url.target_url }}</a>
</p>
consists of {{ url.target_url_len }} characters, and resulted in a URL which is {{ url.short_url_len }} characters long:
<p class="indent_link">
	<a href="{{ url.short_url }}">{{ url.short_url }}</a>
</p>
<p class="indent_link">
	<a href="{{ url.base_url }}/preview/{{ url.hash }}">{{ url.base_url }}/preview/{{ url.hash }}</a>
</p>

{% if preview_image_small %}
preview image (<a href="/{{ preview_image_large }}">click for larger view</a>):
<a href="/{{ preview_image_large }}"><img src="/{{ preview_image_small }}" /></a>

{% endif %}

{% endblock %}

templates/result.html
{% extends "base.html" %}

{% block title %}Shorten a URL{% endblock %}

{% block content %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p><br />{% endif %}
Shortened URL: <a href="http://u.bf2e.com/{{ hash }}">http://u.bf2e.com/{{ hash }}</a> 
<br />
<a href="/">home</a>
{% endblock %}

templates/url_form.html
<form method="post" action="/create/" class="urlform">
<div>
    <div>
		{{ url_form.path.errors }}
		<label for="id_path">Url to make short:</label>
		<br />
		{{ url_form.path }}
    <input type="submit" value="Shorten!"/>
    </div>
{% if allow_custom %}
	<div>
		<label for="id_hash">Request short name (optional):</label>
		<br />
		{{ url_form.hash }}
	</div>
{% endif %}
</div>
</form>